
[19:25:19] --- Big Bot is online.
[19:32:15] --- Big Bot is online.
[19:34:48] --- Big Bot is online.
[21:03:37] --- Big Bot is online.
[21:04:13] --- Big Bot is online.
[21:09:39] --- Big Bot is online.
[21:09:46] --- Ping command, with latency:220
[21:18:54] --- Big Bot is online.
[21:19:05] --- Ping command, with latency:253
[21:19:26] --- Error: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
[21:20:55] --- Big Bot is online.
[21:21:01] --- Error: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
[21:25:01] --- Big Bot is online.
[21:25:04] --- Error: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
[21:31:35] --- Big Bot is online.
[21:31:38] --- Error: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
[21:31:59] --- Big Bot is online.
[21:32:05] --- Error: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
[21:33:34] --- Big Bot is online.
[21:33:37] --- Error: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
[21:34:18] --- Big Bot is online.
[21:34:19] --- Error: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
[21:35:59] --- Big Bot is online.
[21:36:00] --- Error: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
[21:37:45] --- Error: Command raised an exception: KeyError: 162125806137638912
[21:40:11] --- Big Bot is online.
[21:40:13] --- Error: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
[21:41:31] --- Big Bot is online.
[21:41:34] --- Error: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
[21:42:03] --- Big Bot is online.
[21:42:04] --- Error: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
[21:54:23] --- Big Bot is online.
[21:54:27] --- Error: Command raised an exception: FileNotFoundError: [WinError 2] The system cannot find the file specified: '../logs'
[21:55:27] --- Error: Command raised an exception: ClientException: ffmpeg was not found.
[21:55:52] --- Error: Command raised an exception: FileNotFoundError: [WinError 2] The system cannot find the file specified: '../logs'
[21:57:37] --- Big Bot is online.
[21:57:39] --- Connected to voice channel.
[21:57:47] --- Error: Command raised an exception: ClientException: ffmpeg was not found.
[21:59:22] --- Left voice channel.
[21:59:29] --- Big Bot is online.
[21:59:34] --- Connected to voice channel.
[21:59:36] --- Error: Command raised an exception: ClientException: ffmpeg was not found.
[22:00:29] --- Left voice channel.
[22:00:34] --- Big Bot is online.
[22:00:37] --- Connected to voice channel.
[22:00:39] --- Error: Command raised an exception: ClientException: ffmpeg was not found.
[22:02:17] --- Big Bot is online.
[22:02:23] --- Connected to voice channel.
[22:02:26] --- Error: Command raised an exception: ClientException: ffmpeg was not found.
[22:03:13] --- Big Bot is online.
[22:03:17] --- Connected to voice channel.
[22:03:20] --- Error: Command raised an exception: ClientException: ffmpeg was not found.
[22:04:10] --- Big Bot is online.
[22:04:12] --- Connected to voice channel.
[22:04:15] --- Error: Command raised an exception: KeyError: 'ffmpegPATH'
[22:04:35] --- Big Bot is online.
[22:04:37] --- Connected to voice channel.
[22:04:40] --- Error: Command raised an exception: PermissionError: [WinError 5] Access is denied
[22:05:53] --- Big Bot is online.
[22:06:00] --- Connected to voice channel.
[22:06:02] --- Error: Command raised an exception: PermissionError: [WinError 5] Access is denied
[22:06:36] --- Big Bot is online.
[22:06:39] --- Connected to voice channel.
[22:06:54] --- Error: Command raised an exception: PermissionError: [WinError 5] Access is denied
[22:06:56] --- Ping command, with latency:214
[22:06:56] --- Error: Command raised an exception: PermissionError: [WinError 5] Access is denied
[22:08:10] --- Big Bot is online.
[22:08:15] --- Connected to voice channel.
[22:08:18] --- Error: Command raised an exception: PermissionError: [WinError 5] Access is denied
[22:09:33] --- Big Bot is online.
[22:10:08] --- Ping command, with latency:250
[22:10:17] --- Error: Command raised an exception: PermissionError: [WinError 5] Access is denied
[22:10:51] --- Big Bot is online.
[22:11:02] --- Connected to voice channel.
[22:11:04] --- Error: Command raised an exception: PermissionError: [WinError 5] Access is denied
[22:13:12] --- Big Bot is online.
[22:13:13] --- Connected to voice channel.
[22:13:16] --- Error: Command raised an exception: PermissionError: [WinError 5] Access is denied
[22:14:11] --- Error: Command raised an exception: FileNotFoundError: [WinError 2] The system cannot find the file specified: '../bank'
[22:17:19] --- Big Bot is online.
[22:19:57] --- Big Bot is online.
[22:20:06] --- Error: Command raised an exception: KeyError: '160297704998567936'
[22:21:19] --- Big Bot is online.
[22:21:23] --- Error: Command raised an exception: KeyError: '160297704998567936'
[22:21:54] --- Big Bot is online.
[22:21:55] --- Error: Command raised an exception: KeyError: '160297704998567936'
[22:22:29] --- Big Bot is online.
[22:22:30] --- Error: Command raised an exception: KeyError: '160297704998567936'
[22:25:36] --- Big Bot is online.
[22:25:51] --- Error: Command raised an exception: TypeError: string indices must be integers
[22:26:06] --- Big Bot is online.
[22:26:13] --- Error: Command raised an exception: TypeError: string indices must be integers